name: Deploy Airflow Code to GCS-dev

on:
  pull_request:
    types:
      - closed # The workflow triggers when the PR is closed (merged or rejected)
    branches:
      - airflow_development 

env:
  GCS_BUCKET_NAME: ${{ secrets.AIRFLOW_DEV_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Only proceed if the PR was merged
    - name: Check if PR was merged
      if: github.event.pull_request.merged == true
      run: echo "PR was merged, proceeding with deployment."

    - name: Set up Google Cloud SDK
      if: github.event.pull_request.merged == true
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GCP_DEV_PROJECT_ID }} 
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Set GCS bucket variable
      if: github.event.pull_request.merged == true
      run: echo "GCS_BUCKET_NAME=$GCS_BUCKET_NAME" >> $GITHUB_ENV  

    - name: Push entire repo to GCS
      if: github.event.pull_request.merged == true
      run: |
            AIRFLOW_BUCKET="gs://${{ secrets.AIRFLOW_DEV_BUCKET }}"
            gsutil rsync -r . $AIRFLOW_BUCKET



