name: Deploy Airflow Code to GCS-dev

on:
  pull_request:
    types:
      - closed # The workflow triggers when the PR is closed (merged or rejected)
    branches:
      - airflow_development 

env:
  GCS_BUCKET_NAME: ${{ secrets.AIRFLOW_DEV_BUCKET }}
  GCP_PROJECT_ID: ${{ secrets.GCP_DEV_PROJECT_ID }}  
  GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Only proceed if the PR was merged
    - name: Check if PR was merged
      if: github.event.pull_request.merged == true
      run: echo "PR was merged, proceeding with deployment."

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.7.0
      with:
        project_id: $GCP_PROJECT_ID
        credentials_json: $GCP_CREDENTIALS_JSON

    - name: Verify gcloud installation
      run: gcloud --version

    - name: Set GCS bucket variable
      run: echo "GCS_BUCKET_NAME=$GCS_BUCKET_NAME" >> $GITHUB_ENV  

    - name: Push entire repo to GCS
      run: |
            AIRFLOW_BUCKET="gs://$GCS_BUCKET_NAME"
            gsutil -m rsync -r --exclude ".git/**" --exclude ".github/**" ./ $AIRFLOW_BUCKET


