name: Deploy Airflow Code to GCS-dev

on:
  pull_request:
    types:
      - closed # The workflow triggers when the PR is closed (merged or rejected)
    branches:
      - airflow-development
  workflow_dispatch: 

env:
  AIRFLOW_BUCKET: "gs://${{ secrets.AIRFLOW_DEV_BUCKET }}"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Only proceed if the PR was merged
    - name: Check if PR was merged
      if: github.event.pull_request.merged == true
      run: echo "PR was merged, proceeding with deployment."

    - name: Set up Google Cloud SDK
      if: github.event.pull_request.merged == true
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.GCP_DEV_PROJECT_ID }} 
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - name: Push dags/ to GCS
      if: github.event.pull_request.merged == true
      run: |
            gcloud storage rsync dags/ $AIRFLOW_BUCKET/dags \
            --recursive \
            --exclude=".DS_Store" \
            --delete-unmatched-destination-objects

            gcloud storage cp requirements.txt $AIRFLOW_BUCKET/requirements.txt

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.failing-job.result == 'failure' || needs.failing-job.result == 'timed_out') }}
    needs:
      - deploy
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: GHA
        SLACK_TITLE: Workflow ${{ needs.deploy.result }}
        MSG_MINIMAL: actions url
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

